name: Java CI

on: [push, pull_request]

jobs:
  build:
    name: BuildTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up JDK 22
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '22'

      - name: Compile Java program
        run: javac Main.java
